packages:
  - "apps/*"
  - "packages/*"
catalogs:
  build:
    "@rollup/plugin-babel": ^6.0.4
    "@rollup/plugin-commonjs": ^25.0.8
    "@rollup/plugin-json": ^6.1.0
    "@rollup/plugin-node-resolve": ^15.3.0
    "@rollup/plugin-replace": ^6.0.2
    "@rollup/plugin-terser": ^0.4.4
    "@rollup/plugin-typescript": 12.1.2
    rollup: ^4.24.4
    vite: ^5.4.10
  cli:
    "@changesets/changelog-github": ^0.5.0
    "@changesets/cli": ^2.27.9
  dev:
    "@babel/core": ^7.26.0
    chrome-types: 0.1.321
    happy-dom: ^13.10.1
    typescript: ^5.8.3
  i18n:
    i18next: ^23.16.4
  lint:
    "@eslint/js": ^9.27.0
    eslint: ^9.27.0
    husky: ^9.1.7
    lint-staged: ^16.1.0
    prettier: ^3.3.3
    typescript-eslint: ^8.32.1
  markdown:
    mdast-util-to-markdown: ^2.1.2
  monorepo:
    turbo: ^2.5.3
  network:
    browser-fs-access: ^0.35.0
  node:
    "@babel/preset-env": ^7.26.0
    execa: ^9.5.1
    glob: ^10.4.5
    globals: ^16.2.0
  prod:
    "@zip.js/zip.js": ^2.7.53
    core-js: 3.36.0
    es-toolkit: ^1.39.5
    filenamify: ^6.0.0
    js-base64: ^3.7.7
    mdast-util-gfm-strikethrough: ^2.0.0
    mdast-util-gfm-table: ^2.0.0
    mdast-util-gfm-task-list-item: ^2.0.0
    mdast-util-math: ^3.0.0
    radash: ^12.1.0
    serialize-error: ^12.0.0
    tslib: ^2.8.1
  test:
    vitest: ^1.6.0
  types:
    "@types/lodash-es": ^4.17.12
    "@types/mdast": ^4.0.4
    "@types/node": 22.12.0
  utils:
    lodash-es: ^4.17.21
